version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.16.0

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - ./.npm
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Check formatting
          command: npm run format:check
      - run:
          name: Build site
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - public/*

  deploy:
    docker:
      - image: circleci/node:8.16.0
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - ./.npm
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Set git username and password
          command: |
            git config user.email "sayler.b@gmail.com"
            git config user.name "Brian Sayler"
      - add_ssh_keys:
          fingerprints:
            - "7f:32:e5:25:3c:cf:9b:6c:d5:66:46:52:c8:dc:5c:eb"
      - run:
          name: Deploy to github pages
          command: npm run deploy:ci

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: source
